config/routes.rb
Rails.application.routes.draw do
 resources :boards do
  resources :comments, only: [:create, :destroy]
 end
 
 root to: 'boards#index'
end

app/models/board.rb
class Board < ActiveRecord::Base
 has_many :comments, dependent: :destroy

 validates :title,  presence: true, length: { in: 4..127 }
 validates :editor, presence: true, length: { in: 4..30 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 belongs_to :board

 validates :board, presence: true
 validates :name, presence: true
 validates :content, presence: true, length: { in: 1..1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
 class BoardsController < ApplicationController

  def index
   @boards = Board.all
  end

  def show
   @board = Board.includes(:comments).find(params[:id])
   @comment = Comment.new
  end

  def new
   @board = Board.new
  end

  def create
   @board = Board.new(params_board)
   if @board.save
     redirect_to board_url(@board)
   else
     render "new"
   end
  end

  def edit
   @board = Board.find(params[:id])
  end

  def update
   @board = Board.find(params[:id])
   if @board.update_attributes(params_board)
    redirect_to board_url(@board)
   else
    render "edit"
   end
  end

  def destroy
   @board = Board.find(params[:id])
   @board.destroy
   redirect_to boards_url
  end

  private

   def params_board
    params.require(:board).permit(:title, :editor)
   end

 end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def create
  @board = Board.find(params[:board_id])
  @comment = Comment.new(params_comment)
  @comment.board = @board

  if @comment.save
   redirect_to board_url(@board)
  else
   render "boards/show"
  end
 end

 def destroy
  @board = Board.find(params[:board_id])
  @comment = Comment.find(params[:id])
  @comment.destroy
  redirect_to board_url(@board)
 end

 private

  def params_comment
   params.require(:comment).permit(:name, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.erb
<div class="wrapper wrapper__bg">
 <div class="container">
  <%= link_to @board.title, board_path(@board) %>
  <hr>
  <h1>Boards#edit</h1>
  <% if @board.errors.any? %>
  <%= @board.errors.full_messages %>
  <% end %>
  <div class="panel form">
   <%= form_for @board do |f| %>
   <div>
    <div class="form--label">タイトル: </div>
    <div class="form--input">
     <%= f.text_field :title %>
    </div>
   </div>
   <div>
   <div class="form--label">作成者名:</div>
    <div class="form--input">
     <%= f.text_field :editor %>
    </div>
   </div>
   <%= f.submit %>
   <% end %>
  </div>
 </div>
</div>

app/views/boards/index.html.erb
<div class="wrapper wrapper__bg">
 <div class="container">
  <h1>2chクローン</h1>
  <%= link_to "Create new thread", new_board_path %>
  <hr>
   <div class="panel">
    <% @boards.each do |board| %>
     <%= link_to board.title, board_path(board) %><br>
    <% end %>
   </div>
 </div>
</div>

app/views/boards/new.html.erb
<div class="wrapper wrapper__bg">
 <div class="container">
  <%= link_to "Back to thread list", boards_path %>
  <hr>
  <h1>Boards#new</h1>
  <% if @board.errors.any? %>
    <%= @board.errors.full_messages %>
  <% end %>
  <div class="panel form">
   <%= form_for @board do |f| %>
   <div>
    <div class="form--label">Title: </div>
    <div class="form--input">
     <%= f.text_field :title  %>
    </div>
   </div>
   <div>
    <div class="form--label">Creator: </div>
    <div class="form--input"> 
     <%= f.text_field :editor %>
    </div>
   </div>
   <%= f.submit %>
   <% end %>
  </div>
 </div>
</div>

app/views/boards/show.html.erb
<div class="wrapper wrapper__bg">
 <div class="container">
  <%= link_to "back to thread list", boards_path %>
  <hr>
  <div class="board">
   <h1 class="board--name"><%= @board.title %></h1>
  </div>
  <%= link_to "Edit title", edit_board_path %>
  <%= link_to "Delete", board_path(@board), method: :delete, data: { confirm: "Delete this thread?" } %>
  <hr>
  <div class="comment">
   <% @board.comments.each_with_index do |comment, index| %>
   <div class="comment">
    <div class="comment--heading">
     <%= index + 1 %>:
     <%= comment.name %>:
     <%= comment.created_at.strftime("%Y/%m/%d %H:%M:%S ") %>:
     <%= link_to "Delete", board_comment_path(@board, comment), method: :delete, data: { confirm: "Delete this comment?" } %> <br>
    </div>
    <div class="comment--body">
     <%= comment.content %>
    </div>
   </div>
   <% end %>
  </div>
  <hr>
  <%= form_for @comment, url: board_comments_path(@board, @comment) do |f| %>
   Name:    <%= f.text_field :name    %> <br>
   Comment: <%= f.text_area  :content %> <br>
   <%= f.submit %>
  <% end %>
 </div>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>2ch clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>